services:
  - type: web
    name: telegram-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TOKEN
        fromGroup: telegram-bot-env
      - key: MAIN_USER_ID
        fromGroup: telegram-bot-env
      - key: USERS
        fromGroup: telegram-bot-env